# Intro python data science
## Práctica 03: Paquetes

Veremos lo sigueinte:
* Punto 1: Qué son los paquetes y su uso
* Punto 2: Diferencias entre funciones y métodos
* Punto 3: Paquetes básicos en ciencia de datos

# Punto 1:

In [25]:
# importar un paquete
import numpy


In [26]:
numpy.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
# importar un paquete con acrónimo
import numpy as np

In [28]:
# objeto array de numpy
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# cargar una función específica de un paquete

In [30]:
from numpy import arange

In [31]:
arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Punto 2:

In [32]:
# Diferencias entre funciones y métodos

In [33]:
A=np.arange(16)

In [34]:
# que tipo de objeto es A
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
type(A)

numpy.ndarray

In [36]:
# calculando promedio con función de numpy
np.mean(A)

7.5

In [37]:
# calculando promedio con método de objetonp.mean(A)
A.mean()

7.5

In [38]:
# Haciendo un reshape con funciones y métodos


In [39]:
# transformando arreglo con función de numpy
np.reshape(A, (4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
# transformando arreglo con método de objeto
A.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
A.metodo1().metodo2().metodo3()

AttributeError: 'numpy.ndarray' object has no attribute 'metodo1'

# Listas!
## Bueno Practicando DS-Notebook 😀

